### ISSUE TITLE
`@typescript-eslint` breaks after update to `eslint-plugin-ember` v12

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/eslint-plugin-ember#2062] opened 2024-01-15 16:01 UTC
With version `11.12.0` (and everything else at the latest version) all works fine. Upgrading to v12 I get 400+ errors from ESLint. As far as I see, all are from `@typescript-eslint`. The vast majority are `'any' overrides all other types in this union type  @typescript-eslint/no-redundant-type-constituents` (not sure if that matters).

Anyone else hit this problem? Any ideas what might be happening?

**Comment by NullVoxPopuli** [comment] 2024-01-15 16:13
in V11, type-aware lint rules were not able to run on gts files, now they are -- are you seeing something outside of the expected behavior from `@typescript-eslint/no-redundant-type-constituents`?

**Comment by boris-petrov** [comment] 2024-01-15 16:16
I should have mentioned that I'm not using GTS files yet, still on the "old" Ember style (but on the latest version).

Yes, all of these new errors that I get are bogus - they don't make sense. At least I think so.

**Comment by NullVoxPopuli** [comment] 2024-01-15 16:18
Any chance you could create a reproduction repo?
I'm curious why, if you aren't using gts, why typescript-eslint rules are active at all?

Can you provide your config?

**Comment by boris-petrov** [comment] 2024-01-15 16:20
I'm using TS, why wouldn't they be active? I'm just not using GTS.

My config is pretty big. If you can't think of anything on the top of your head what might be happening, I'll try creating a reproduction shortly.

**Comment by NullVoxPopuli** [comment] 2024-01-15 16:21
Are you importing from gjs? perhaps? 

but yeah, a reproduction would be most helpful, as I don't have an ideas for anything that would cause the behavior you're seeing

**Comment by boris-petrov** [comment] 2024-01-15 16:22
No, I don't have any GTS in my code (and I guess I don't have in my plugins either?).

**Comment by bmish** [comment] 2024-01-15 19:36
Our new dependency on [ember-eslint-parser](https://github.com/NullVoxPopuli/ember-eslint-parser) could bring in some [newer](https://github.com/NullVoxPopuli/ember-eslint-parser/blob/main/package.json) TypeScript dependencies. Could that be related?

**Comment by boris-petrov** [comment] 2024-01-15 19:40
@bmish it could be, however, I'm on the newest version of everything so... not sure.

[Here is a repo](https://github.com/boris-petrov/eslint-plugin-ember-bug). Clone and run `pnpm lint:js`. You'll see the error. Funny thing is that downgrading doesn't seem to fix it... it does on my project. And the minified version of my project that I was trying while reproducing...

If anyone has ideas... for me there is something very strange going on.

**Comment by boris-petrov** [comment] 2024-01-15 19:45
No, wait. This error seems to appear if the import is not found. If you change `../store` to `asdf/services/store` it will fail in that way. In my project the Ember app is in a folder called `frontend` and all my imports are like `frontend/services/store`. Could this have somehow changed?

**Comment by NullVoxPopuli** [comment] 2024-01-15 19:46
it's possible your tsconfig resolution settings aren't expecting extensionless imports?

I'll dive in to your repro tomorrow

**Comment by boris-petrov** [comment] 2024-01-15 20:24
I believe my `tsconfig` should be fine but I can't be sure. In any case, please check out the reproduction. Run `pnpm i` and then `pnpm lint:js`. You'll see the error. Downgrading to `11.12.0` fixes the issue.

**Comment by chancancode** [comment] 2024-02-13 03:55
I have also attempted to upgrade and ran into the same issue. I attempted to make sure everything `@typescript-eslint` is already up-to-date before the `eslint-plugin-ember` upgrade itself to isolate the issue as much as possible.

Here is the upgrade diff: https://gist.github.com/chancancode/966bf0ff4df59c919839113f368b1a7a

I also tried deleting the eslint cache (before/after the upgrade) just to be sure, but doesn't seem to be the case either.

It definitely seems like something about this upgrade broke something in the module graph, either things are not resolving, or some module isn't able to be parsed correctly, and causing that to cascade outwards.

It's causing non-ember related errors like these:

<img width="601" alt="Screen Shot 2024-02-12 at 7 50 30 PM" src="https://github.com/ember-cli/eslint-plugin-ember/assets/55829/9ad2fa78-e287-40fa-91fb-216f553cabe0">

Here, `this.modelFor()` has a return type of `unknown` so the only reason eslint complains about `any` would be because the `AppComponent` import failed to resolve and became `any`.

I have a pretty strong hunch that the problem is we somehow broke support for `import type`, and that they are silently getting ignored (the errors are as if you comment out all the `import type` lines).

**Closed** 2024-02-13 13:33 UTC
Labels: Bug

**Comment by bmish** [comment] 2024-02-13 15:05
Relevant discord discussion: https://discord.com/channels/480462759797063690/717767358743183412/1206812615985336320

**Comment by boris-petrov** [comment] 2024-02-13 16:21
Thank you for working on this!

However, the new version (12.0.1) doesn't seem to fix either the problem in my repo, or the [reproduction](https://github.com/boris-petrov/eslint-plugin-ember-bug) I gave above. Can someone check?

**Comment by NullVoxPopuli** [comment] 2024-02-13 17:11
your lockfile needs refreshed -- it's using a very old parser

**Comment by boris-petrov** [comment] 2024-02-13 17:15
@NullVoxPopuli it's not that. I pushed another commit that updates everything. Still doesn't work.

**Comment by boris-petrov** [comment] 2024-02-13 17:20
It's a bug in `eslint-plugin-ember`. [This](https://github.com/ember-cli/eslint-plugin-ember/blob/v12.0.1/package.json#L77) doesn't allow `0.3.x`.

**Comment by NullVoxPopuli** [comment] 2024-02-13 17:34
PR to update here: https://github.com/ember-cli/eslint-plugin-ember/pull/2091
