### ISSUE TITLE
New rule: `call-super`

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/eslint-plugin-ember#97] opened 2017-07-13 11:07 UTC
In almost all cases you should call `this._super(...arguments);` when overriding methods.

Without inspecting the prototype chain, we can't guard for all possible overwrites, however we can at least guard for known methods provided by Ember. For example, overriding `didReceiveAttrs` in a component should prompt you to call `this._super` in that method.

Side note regarding #96: for ES6 classes it's `super.didReceiveAttrs(...arguments);` or `super(...arguments);` for the `constructor`. This does not fully work yet though: https://github.com/rwjblue/ember-decorators/issues/120#issuecomment-314750389

**Comment by michalsnik** [comment] 2017-07-13 11:53
Hey @buschtoens, thanks for this proposition, but I think it's kind of a duplicate of #82 isn't it? If yes then we can continue this conversation there. If not - please reopen this issue :)

**Closed by michalsnik** 2017-07-13 11:53 UTC

**Comment by buschtoens** [comment] 2017-07-13 12:49
Whoops, my bad.
