### ISSUE TITLE
Extends `require-super-in-init` to all lifecycle hooks

### ISSUE THREAD

**Issue by cbou** [ember-cli/eslint-plugin-ember#275] opened 2018-08-04 11:11 UTC
I had an issue on a project because I forgot to add `this._super(...arguments);` in the willDestroyElement hook.

I think it would make sense to extend the rule `require-super-in-init` to all lifecycle hooks.

**Comment by Alonski** [comment] 2018-12-31 07:59
Just mentioning that this seems to be a duplicate of #228

**Comment by bmish** [comment] 2019-08-04 22:46
Closing as duplicate of #228.

**Closed** 2019-08-04 22:45 UTC
Labels: Enhancement
