### ISSUE TITLE
"Cannot read property 'name' of undefined" error when using object spread

### ISSUE THREAD

**Issue by Kerrick** [ember-cli/eslint-plugin-ember#284] opened 2018-09-19 18:56 UTC
Clone https://github.com/Kerrick/eslint-plugin-ember-bug and run `ember test` to see the following error:

```
Build failed.
Build Error (broccoli-persistent-filter:EslintValidationFilter) in transforms/comma-delimited-integers.js

Cannot read property 'name' of undefined
```

[Relevant app code](https://github.com/Kerrick/eslint-plugin-ember-bug/blob/37a08a5c4c2bb818b497f59e199d931aa37acb99/app/transforms/semicolon-delimited-strings.js#L4-L6):
```js
export default DS.Transform.extend({
  ...delimited({ split: ';' })
});
```

<summary>
Full stack trace
<details>

```
ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'name' of undefined
    at CallExpression.properties.filter.property (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint-plugin-ember\lib\rules\avoid-leaking-state-in-ember-objects.js:69:69)
    at Array.filter (native)
    at CallExpression (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint-plugin-ember\lib\rules\avoid-leaking-state-in-ember-objects.js:69:12)
    at listeners.(anonymous function).forEach.listener (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
  - codeFrame: Cannot read property 'name' of undefined
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:EslintValidationFilter` plugin. ðŸ’¥
Cannot read property 'name' of undefined
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: transforms/comma-delimited-integers.js
    - line: [undefined]
    - treeDir: C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\tmp\broccoli_persistent_filtereslint_validation_filter-input_base_path-ZMPaEOyX.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:EslintValidationFilter` plugin. ðŸ’¥
Cannot read property 'name' of undefined
  - name: Error
  - nodeAnnotation: broccoli-persistent-filter:EslintValidationFilter
  - nodeName: broccoli-persistent-filter:EslintValidationFilter
  - originalErrorMessage: Cannot read property 'name' of undefined
  - stack: TypeError: Cannot read property 'name' of undefined
    at CallExpression.properties.filter.property (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint-plugin-ember\lib\rules\avoid-leaking-state-in-ember-objects.js:69:69)
    at Array.filter (native)
    at CallExpression (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint-plugin-ember\lib\rules\avoid-leaking-state-in-ember-objects.js:69:12)
    at listeners.(anonymous function).forEach.listener (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Users\kerrick\Temporary\eslint-plugin-ember-bug\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
```

</details>
</summary>

Relevant eslint-plugin-ember code:

https://github.com/ember-cli/eslint-plugin-ember/blob/236bd7d7ed2988a4d14bfaa9b49b6e381bcb6ef9/lib/rules/avoid-leaking-state-in-ember-objects.js#L68-L74

**Comment by Turbo87** [comment] 2018-09-24 07:28
@Kerrick thanks for the reproduction. are you able to derive a failing test case for that?

**Comment by bmish** [comment] 2019-11-06 17:43
Looks like this was fixed by https://github.com/ember-cli/eslint-plugin-ember/pull/353

**Closed by bmish** 2019-11-06 17:43 UTC
Labels: Bug
