### ISSUE TITLE
DeprecationWarning about 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' eslint-plugin-ember v5.2.0

### ISSUE THREAD

**Issue by amit-srivastava-007** [ember-cli/eslint-plugin-ember#273] opened 2018-07-27 12:11 UTC
I am continuously getting error while running eslint
```
(node:12836) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: 
The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. 
Use 'parserOptions.ecmaVersion' instead. 
(found in "node_modules\eslint-plugin-ember\lib\config\base.js")
```

```
node v8.11.3
npm v5.6.0
ember-cli v3.3.0
eslint v5.2.0
eslint-plugin-ember v5.2.0
```

any suggestion?

**Comment by rwjblue** [comment] 2018-07-27 13:16
Duplicate of https://github.com/ember-cli/eslint-plugin-ember/issues/271

**Closed by rwjblue** 2018-07-27 13:16 UTC
